import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  decimal,
  boolean,
  date,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { companies, fiscalYears, costCenters } from "./core";
import { users } from "./auth";

// =============================================================================
// 1. CHART OF ACCOUNTS — Plano de contas hierárquico COMPLETO
// =============================================================================
export const chartOfAccounts = pgTable(
  "accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    accountCode: varchar("account_code", { length: 50 }).notNull(),
    accountName: varchar("account_name", { length: 255 }).notNull(),
    accountType: varchar("account_type", { length: 50 }).notNull(), // asset, liability, equity, income, expense
    accountSubtype: varchar("account_subtype", { length: 50 }), // bank, cash, receivable, payable, fixed_asset, current_asset, long_term_asset, current_liability, long_term_liability, equity, revenue, cost_of_goods, operating_expense, non_operating_expense
    rootType: varchar("root_type", { length: 50 }).notNull(),
    parentAccountId: uuid("parent_account_id"),
    isGroup: boolean("is_group").default(false).notNull(),
    isFrozen: boolean("is_frozen").default(false).notNull(),
    isInternal: boolean("is_internal").default(false).notNull(),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    balance: decimal("balance", { precision: 20, scale: 4 }).default("0").notNull(),
    debitBalance: decimal("debit_balance", { precision: 20, scale: 4 }).default("0").notNull(),
    creditBalance: decimal("credit_balance", { precision: 20, scale: 4 }).default("0").notNull(),
    description: text("description"),
    taxRate: decimal("tax_rate", { precision: 5, scale: 2 }),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("accounts_tenant_id_idx").on(t.tenantId),
    index("accounts_company_id_idx").on(t.companyId),
    index("accounts_type_idx").on(t.accountType),
    index("accounts_subtype_idx").on(t.accountSubtype),
    index("accounts_parent_idx").on(t.parentAccountId),
    uniqueIndex("accounts_code_company_idx").on(t.accountCode, t.companyId),
  ]
);

// =============================================================================
// 2. JOURNAL ENTRIES — Lançamentos contábeis COMPLETO
// =============================================================================
export const journalEntries = pgTable(
  "journal_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    fiscalYearId: uuid("fiscal_year_id")
      .notNull()
      .references(() => fiscalYears.id),
    entryNumber: varchar("entry_number", { length: 50 }).notNull(),
    entryDate: date("entry_date").notNull(),
    postingDate: date("posting_date").notNull(),
    voucherType: varchar("voucher_type", { length: 50 }).notNull(), // journal_entry, sales_invoice, purchase_invoice, payment_entry, depreciation_entry
    voucherNumber: varchar("voucher_number", { length: 50 }),
    narration: text("narration"),
    companyRemarks: text("company_remarks"),
    userRemarks: text("user_remarks"),
    referenceType: varchar("reference_type", { length: 50 }),
    referenceName: varchar("reference_name", { length: 255 }),
    totalDebit: decimal("total_debit", { precision: 20, scale: 4 }).default("0").notNull(),
    totalCredit: decimal("total_credit", { precision: 20, scale: 4 }).default("0").notNull(),
    totalAmount: decimal("total_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    isAmended: boolean("is_amended").default(false).notNull(),
    amendedFrom: uuid("amended_from"),
    isAutoGenerated: boolean("is_auto_generated").default(false).notNull(),
    status: varchar("status", { length: 20 }).default("draft").notNull(), // draft, submitted, cancelled, voided
    costCenterId: uuid("cost_center_id"),
    createdBy: uuid("created_by").references(() => users.id),
    submittedBy: uuid("submitted_by").references(() => users.id),
    submittedAt: timestamp("submitted_at"),
    cancelledBy: uuid("cancelled_by").references(() => users.id),
    cancelledAt: timestamp("cancelled_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("journal_entries_tenant_id_idx").on(t.tenantId),
    index("journal_entries_company_id_idx").on(t.companyId),
    index("journal_entries_date_idx").on(t.entryDate),
    index("journal_entries_posting_date_idx").on(t.postingDate),
    index("journal_entries_status_idx").on(t.status),
    index("journal_entries_voucher_type_idx").on(t.voucherType),
    index("journal_entries_fiscal_year_idx").on(t.fiscalYearId),
    index("journal_entries_cost_center_idx").on(t.costCenterId),
    uniqueIndex("journal_entries_number_company_idx").on(t.entryNumber, t.companyId),
  ]
);

// =============================================================================
// 3. JOURNAL ENTRY LINES — Linhas dos lançamentos COMPLETO
// =============================================================================
export const journalEntryLines = pgTable(
  "journal_entry_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    journalEntryId: uuid("journal_entry_id")
      .notNull()
      .references(() => journalEntries.id, { onDelete: "cascade" }),
    accountId: uuid("account_id")
      .notNull()
      .references(() => chartOfAccounts.id),
    debit: decimal("debit", { precision: 20, scale: 4 }).default("0").notNull(),
    credit: decimal("credit", { precision: 20, scale: 4 }).default("0").notNull(),
    exchangeRate: decimal("exchange_rate", { precision: 20, scale: 10 }).default("1"),
    referenceType: varchar("reference_type", { length: 50 }),
    referenceName: varchar("reference_name", { length: 255 }),
    costCenterId: uuid("cost_center_id"),
    description: text("description"),
    projectName: varchar("project_name", { length: 255 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("journal_entry_lines_tenant_id_idx").on(t.tenantId),
    index("journal_entry_lines_entry_id_idx").on(t.journalEntryId),
    index("journal_entry_lines_account_id_idx").on(t.accountId),
    index("journal_entry_lines_cost_center_idx").on(t.costCenterId),
    index("journal_entry_lines_reference_idx").on(t.referenceType, t.referenceName),
  ]
);

// =============================================================================
// 4. PAYMENT ENTRIES — Entradas de pagamento COMPLETO
// =============================================================================
export const paymentEntries = pgTable(
  "payment_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    partyType: varchar("party_type", { length: 50 }).notNull(), // customer, supplier, employee
    partyId: uuid("party_id").notNull(),
    paymentType: varchar("payment_type", { length: 20 }).notNull(), // receive, pay, internal_transfer
    paymentDate: date("payment_date").notNull(),
    postingDate: date("posting_date").notNull(),
    modeOfPayment: varchar("mode_of_payment", { length: 100 }), // bank_transfer, cash, check, credit_card, debit_card
    paidAmount: decimal("paid_amount", { precision: 20, scale: 4 }).notNull(),
    receivedAmount: decimal("received_amount", { precision: 20, scale: 4 }),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    exchangeRate: decimal("exchange_rate", { precision: 20, scale: 10 }).default("1"),
    sourceAccount: uuid("source_account").references(() => chartOfAccounts.id),
    targetAccount: uuid("target_account").references(() => chartOfAccounts.id),
    referenceNumber: varchar("reference_number", { length: 255 }),
    referenceDate: date("reference_date"),
    clearanceDate: date("clearance_date"),
    remarks: text("remarks"),
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    status: varchar("status", { length: 20 }).default("draft").notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    submittedBy: uuid("submitted_by").references(() => users.id),
    submittedAt: timestamp("submitted_at"),
    bankAccount: uuid("bank_account").references(() => chartOfAccounts.id),
    partyAccount: uuid("party_account").references(() => chartOfAccounts.id),
    isInternalTransfer: boolean("is_internal_transfer").default(false).notNull(),
    taxAmount: decimal("tax_amount", { precision: 20, scale: 4 }).default("0"),
    baseAmount: decimal("base_amount", { precision: 20, scale: 4 }),
    baseReceivedAmount: decimal("base_received_amount", { precision: 20, scale: 4 }),
    unallocatedAmount: decimal("unallocated_amount", { precision: 20, scale: 4 }).default("0"),
    costCenterId: uuid("cost_center_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("payment_entries_tenant_id_idx").on(t.tenantId),
    index("payment_entries_company_id_idx").on(t.companyId),
    index("payment_entries_party_idx").on(t.partyType, t.partyId),
    index("payment_entries_date_idx").on(t.paymentDate),
    index("payment_entries_status_idx").on(t.status),
    index("payment_entries_source_account_idx").on(t.sourceAccount),
    index("payment_entries_target_account_idx").on(t.targetAccount),
    index("payment_entries_mode_idx").on(t.modeOfPayment),
  ]
);

// =============================================================================
// 5. INVOICES — Faturas genéricas COMPLETO
// =============================================================================
export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    invoiceType: varchar("invoice_type", { length: 20 }).notNull(), // sales, purchase
    invoiceNumber: varchar("invoice_number", { length: 50 }).notNull(),
    partyType: varchar("party_type", { length: 50 }).notNull(),
    partyId: uuid("party_id").notNull(),
    invoiceDate: date("invoice_date").notNull(),
    postingDate: date("posting_date").notNull(),
    dueDate: date("due_date"),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    exchangeRate: decimal("exchange_rate", { precision: 20, scale: 10 }).default("1"),
    subtotal: decimal("subtotal", { precision: 20, scale: 4 }).default("0").notNull(),
    taxAmount: decimal("tax_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    discountAmount: decimal("discount_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    totalAmount: decimal("total_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    paidAmount: decimal("paid_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    outstandingAmount: decimal("outstanding_amount", { precision: 20, scale: 4 }).default("0").notNull(),
    paymentTerms: varchar("payment_terms", { length: 100 }),
    paymentTermsTemplateId: uuid("payment_terms_template_id"),
    remarks: text("remarks"),
    status: varchar("status", { length: 20 }).default("draft").notNull(), // draft, submitted, paid, partially_paid, overdue, cancelled
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    createdBy: uuid("created_by").references(() => users.id),
    submittedBy: uuid("submitted_by").references(() => users.id),
    submittedAt: timestamp("submitted_at"),
    cancelledBy: uuid("cancelled_by").references(() => users.id),
    cancelledAt: timestamp("cancelled_at"),
    taxTemplate: varchar("tax_template", { length: 255 }),
    taxTemplateId: uuid("tax_template_id"),
    shippingAddress: text("shipping_address"),
    billingAddress: text("billing_address"),
    advancePaid: decimal("advance_paid", { precision: 20, scale: 4 }).default("0"),
    writeOffAmount: decimal("write_off_amount", { precision: 20, scale: 4 }).default("0"),
    roundingAdjustment: decimal("rounding_adjustment", { precision: 20, scale: 4 }).default("0"),
    baseTotal: decimal("base_total", { precision: 20, scale: 4 }).default("0"),
    baseTaxAmount: decimal("base_tax_amount", { precision: 20, scale: 4 }).default("0"),
    baseTotalAmount: decimal("base_total_amount", { precision: 20, scale: 4 }).default("0"),
    placeOfSupply: varchar("place_of_supply", { length: 100 }),
    isReverseCharge: boolean("is_reverse_charge").default(false).notNull(),
    costCenterId: uuid("cost_center_id"),
    projectCode: varchar("project_code", { length: 100 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("invoices_tenant_id_idx").on(t.tenantId),
    index("invoices_company_id_idx").on(t.companyId),
    index("invoices_party_idx").on(t.partyType, t.partyId),
    index("invoices_date_idx").on(t.invoiceDate),
    index("invoices_due_date_idx").on(t.dueDate),
    index("invoices_status_idx").on(t.status),
    index("invoices_type_idx").on(t.invoiceType),
    index("invoices_cost_center_idx").on(t.costCenterId),
    uniqueIndex("invoices_number_company_idx").on(t.invoiceNumber, t.companyId),
  ]
);

// =============================================================================
// 6. INVOICE LINES — Linhas das faturas COMPLETO
// =============================================================================
export const invoiceLines = pgTable(
  "invoice_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),
    itemId: uuid("item_id"),
    description: varchar("description", { length: 500 }),
    quantity: decimal("quantity", { precision: 20, scale: 4 }).notNull(),
    unitPrice: decimal("unit_price", { precision: 20, scale: 4 }).notNull(),
    discountPercentage: decimal("discount_percentage", { precision: 5, scale: 2 }).default("0"),
    discountAmount: decimal("discount_amount", { precision: 20, scale: 4 }).default("0"),
    taxRate: decimal("tax_rate", { precision: 5, scale: 2 }).default("0"),
    taxAmount: decimal("tax_amount", { precision: 20, scale: 4 }).default("0"),
    taxTemplateId: uuid("tax_template_id"),
    netAmount: decimal("net_amount", { precision: 20, scale: 4 }).notNull(),
    amount: decimal("amount", { precision: 20, scale: 4 }).notNull(),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    costCenterId: uuid("cost_center_id"),
    quantityInStock: decimal("quantity_in_stock", { precision: 20, scale: 4 }),
    unitOfMeasure: varchar("unit_of_measure", { length: 50 }),
    stockLedgerEntryId: uuid("stock_ledger_entry_id"),
    projectName: varchar("project_name", { length: 255 }),
    incomeAccount: uuid("income_account").references(() => chartOfAccounts.id),
    expenseAccount: uuid("expense_account").references(() => chartOfAccounts.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("invoice_lines_tenant_id_idx").on(t.tenantId),
    index("invoice_lines_invoice_id_idx").on(t.invoiceId),
    index("invoice_lines_item_id_idx").on(t.itemId),
    index("invoice_lines_account_id_idx").on(t.accountId),
    index("invoice_lines_cost_center_idx").on(t.costCenterId),
  ]
);

// =============================================================================
// 7. PAYMENT TERMS TEMPLATES — Templates de condições de pagamento
// =============================================================================
export const paymentTermsTemplates = pgTable(
  "payment_terms_templates",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    templateName: varchar("template_name", { length: 255 }).notNull(),
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("payment_terms_templates_tenant_id_idx").on(t.tenantId),
    index("payment_terms_templates_company_id_idx").on(t.companyId),
  ]
);

// =============================================================================
// 8. PAYMENT TERMS TEMPLATE DETAILS — Detalhes das condições de pagamento
// =============================================================================
export const paymentTermsTemplateDetails = pgTable(
  "payment_terms_template_details",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    templateId: uuid("template_id")
      .notNull()
      .references(() => paymentTermsTemplates.id, { onDelete: "cascade" }),
    description: varchar("description", { length: 255 }).notNull(),
    dueByDays: integer("due_by_days").notNull(),
    dueByMonths: integer("due_by_months").default(0),
    discountPercentage: decimal("discount_percentage", { precision: 5, scale: 2 }).default("0"),
    discountByDays: integer("discount_by_days").default(0),
    dueDate: varchar("due_date", { length: 50 }), // end_of_current_month, end_of_next_month, etc.
    modeOfPayment: varchar("mode_of_payment", { length: 100 }),
    rowIndex: integer("row_index").default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("payment_terms_template_details_tenant_id_idx").on(t.tenantId),
    index("payment_terms_template_details_template_id_idx").on(t.templateId),
  ]
);

// =============================================================================
// 9. BANK ACCOUNTS — Contas bancárias COMPLETO
// =============================================================================
export const bankAccounts = pgTable(
  "bank_accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    bankName: varchar("bank_name", { length: 255 }).notNull(),
    accountName: varchar("account_name", { length: 255 }),
    accountNumber: varchar("account_number", { length: 100 }).notNull(),
    branch: varchar("branch", { length: 255 }),
    accountType: varchar("account_type", { length: 50 }).notNull(), // checking, savings, credit_card
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    balance: decimal("balance", { precision: 20, scale: 4 }).default("0").notNull(),
    openingBalance: decimal("opening_balance", { precision: 20, scale: 4 }).default("0"),
    accountCode: varchar("account_code", { length: 50 }),
    glAccountId: uuid("gl_account_id").references(() => chartOfAccounts.id),
    iban: varchar("iban", { length: 100 }),
    swiftCode: varchar("swift_code", { length: 50 }),
    isDefault: boolean("is_default").default(false).notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("bank_accounts_tenant_id_idx").on(t.tenantId),
    index("bank_accounts_company_id_idx").on(t.companyId),
    index("bank_accounts_gl_account_idx").on(t.glAccountId),
    uniqueIndex("bank_accounts_number_company_idx").on(t.accountNumber, t.companyId),
  ]
);

// =============================================================================
// 10. BANK TRANSACTIONS — Transações bancárias COMPLETO
// =============================================================================
export const bankTransactions = pgTable(
  "bank_transactions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    bankAccountId: uuid("bank_account_id")
      .notNull()
      .references(() => bankAccounts.id, { onDelete: "cascade" }),
    transactionDate: date("transaction_date").notNull(),
    postingDate: date("posting_date"),
    description: varchar("description", { length: 500 }).notNull(),
    referenceNumber: varchar("reference_number", { length: 255 }),
    debit: decimal("debit", { precision: 20, scale: 4 }).default("0").notNull(),
    credit: decimal("credit", { precision: 20, scale: 4 }).default("0").notNull(),
    balance: decimal("balance", { precision: 20, scale: 4 }).default("0").notNull(),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    exchangeRate: decimal("exchange_rate", { precision: 20, scale: 10 }).default("1"),
    transactionType: varchar("transaction_type", { length: 50 }), // deposit, withdrawal, transfer, fee, interest
    isReconciled: boolean("is_reconciled").default(false).notNull(),
    reconciledDate: date("reconciled_date"),
    bankReconciliationId: uuid("bank_reconciliation_id"),
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    partyType: varchar("party_type", { length: 50 }),
    partyId: uuid("party_id"),
    remarks: text("remarks"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("bank_transactions_tenant_id_idx").on(t.tenantId),
    index("bank_transactions_company_id_idx").on(t.companyId),
    index("bank_transactions_bank_account_idx").on(t.bankAccountId),
    index("bank_transactions_date_idx").on(t.transactionDate),
    index("bank_transactions_reconciled_idx").on(t.isReconciled),
    index("bank_transactions_reference_idx").on(t.referenceNumber),
  ]
);

// =============================================================================
// 11. BANK RECONCILIATIONS — Conciliações bancárias
// =============================================================================
export const bankReconciliations = pgTable(
  "bank_reconciliations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    bankAccountId: uuid("bank_account_id")
      .notNull()
      .references(() => bankAccounts.id, { onDelete: "cascade" }),
    reconciliationDate: date("reconciliation_date").notNull(),
    bankStatementDate: date("bank_statement_date"),
    openingBalance: decimal("opening_balance", { precision: 20, scale: 4 }).default("0"),
    closingBalance: decimal("closing_balance", { precision: 20, scale: 4 }).default("0"),
    difference: decimal("difference", { precision: 20, scale: 4 }).default("0"),
    isComplete: boolean("is_complete").default(false).notNull(),
    status: varchar("status", { length: 20 }).default("pending").notNull(),
    remarks: text("remarks"),
    createdBy: uuid("created_by").references(() => users.id),
    completedBy: uuid("completed_by").references(() => users.id),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("bank_recon_tenant_idx").on(t.tenantId),
    index("bank_recon_company_idx").on(t.companyId),
    index("bank_recon_bank_account_idx").on(t.bankAccountId),
    index("bank_recon_date_idx").on(t.reconciliationDate),
    index("bank_recon_status_idx").on(t.status),
  ]
);

// =============================================================================
// 12. BANK RECONCILIATION ITEMS — Itens da conciliação bancária
// =============================================================================
export const bankReconciliationItems = pgTable(
  "bank_reconciliation_items",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    reconciliationId: uuid("reconciliation_id")
      .notNull()
      .references(() => bankReconciliations.id, { onDelete: "cascade" }),
    bankTransactionId: uuid("bank_transaction_id")
      .notNull()
      .references(() => bankTransactions.id, { onDelete: "cascade" }),
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    amount: decimal("amount", { precision: 20, scale: 4 }).notNull(),
    isMatched: boolean("is_matched").default(false).notNull(),
    matchedDate: date("matched_date"),
    remarks: text("remarks"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("bank_recon_items_tenant_idx").on(t.tenantId),
    index("bank_recon_items_reconciliation_idx").on(t.reconciliationId),
    index("bank_recon_items_transaction_idx").on(t.bankTransactionId),
    index("bank_recon_items_matched_idx").on(t.isMatched),
  ]
);

// =============================================================================
// 13. BUDGETS — Orçamentos COMPLETO
// =============================================================================
export const budgets = pgTable(
  "budgets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    budgetName: varchar("budget_name", { length: 255 }).notNull(),
    budgetType: varchar("budget_type", { length: 50 }).default("cost_center").notNull(),
    fiscalYearId: uuid("fiscal_year_id")
      .notNull()
      .references(() => fiscalYears.id),
    costCenterId: uuid("cost_center_id").references(() => costCenters.id),
    departmentId: uuid("department_id"),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    totalBudget: decimal("total_budget", { precision: 20, scale: 4 }).notNull(),
    consumedAmount: decimal("consumed_amount", { precision: 20, scale: 4 }).default("0"),
    availableAmount: decimal("available_amount", { precision: 20, scale: 4 }).default("0"),
    monthlyDistribution: jsonb("monthly_distribution").default({}),
    status: varchar("status", { length: 20 }).default("draft").notNull(), // draft, submitted, cancelled, active
    isActive: boolean("is_active").default(true).notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    submittedBy: uuid("submitted_by").references(() => users.id),
    submittedAt: timestamp("submitted_at"),
    cancelledBy: uuid("cancelled_by").references(() => users.id),
    cancelledAt: timestamp("cancelled_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("budgets_tenant_id_idx").on(t.tenantId),
    index("budgets_company_id_idx").on(t.companyId),
    index("budgets_fiscal_year_idx").on(t.fiscalYearId),
    index("budgets_cost_center_idx").on(t.costCenterId),
    index("budgets_account_idx").on(t.accountId),
    index("budgets_status_idx").on(t.status),
  ]
);

// =============================================================================
// 14. BUDGET LINES — Linhas do orçamento COMPLETO
// =============================================================================
export const budgetLines = pgTable(
  "budget_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    budgetId: uuid("budget_id")
      .notNull()
      .references(() => budgets.id, { onDelete: "cascade" }),
    accountId: uuid("account_id")
      .notNull()
      .references(() => chartOfAccounts.id),
    accountCode: varchar("account_code", { length: 50 }),
    accountName: varchar("account_name", { length: 255 }),
    description: text("description"),
    budgetAmount: decimal("budget_amount", { precision: 20, scale: 4 }).notNull(),
    consumedAmount: decimal("consumed_amount", { precision: 20, scale: 4 }).default("0"),
    availableAmount: decimal("available_amount", { precision: 20, scale: 4 }).default("0"),
    jan: decimal("jan", { precision: 20, scale: 4 }).default("0"),
    feb: decimal("feb", { precision: 20, scale: 4 }).default("0"),
    mar: decimal("mar", { precision: 20, scale: 4 }).default("0"),
    apr: decimal("apr", { precision: 20, scale: 4 }).default("0"),
    may: decimal("may", { precision: 20, scale: 4 }).default("0"),
    jun: decimal("jun", { precision: 20, scale: 4 }).default("0"),
    jul: decimal("jul", { precision: 20, scale: 4 }).default("0"),
    aug: decimal("aug", { precision: 20, scale: 4 }).default("0"),
    sep: decimal("sep", { precision: 20, scale: 4 }).default("0"),
    oct: decimal("oct", { precision: 20, scale: 4 }).default("0"),
    nov: decimal("nov", { precision: 20, scale: 4 }).default("0"),
    dec: decimal("dec", { precision: 20, scale: 4 }).default("0"),
    costCenterId: uuid("cost_center_id").references(() => costCenters.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("budget_lines_tenant_id_idx").on(t.tenantId),
    index("budget_lines_budget_id_idx").on(t.budgetId),
    index("budget_lines_account_id_idx").on(t.accountId),
    index("budget_lines_cost_center_idx").on(t.costCenterId),
  ]
);

// =============================================================================
// 15. TAX TEMPLATES — Templates de imposto
// =============================================================================
export const taxTemplates = pgTable(
  "tax_templates",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    templateName: varchar("template_name", { length: 255 }).notNull(),
    taxType: varchar("tax_type", { length: 50 }).notNull(), // vat, gst, sales_tax, service_tax, withholding_tax
    taxCategory: varchar("tax_category", { length: 50 }), // standard, reduced, exempt, zero_rated, reverse_charge
    rate: decimal("rate", { precision: 5, scale: 2 }).notNull(),
    isInclusive: boolean("is_inclusive").default(false).notNull(),
    taxAccountId: uuid("tax_account_id").references(() => chartOfAccounts.id),
    baseAccountId: uuid("base_account_id").references(() => chartOfAccounts.id),
    minimumTaxableAmount: decimal("minimum_taxable_amount", { precision: 20, scale: 4 }),
    maximumTaxableAmount: decimal("maximum_taxable_amount", { precision: 20, scale: 4 }),
    placeOfSupply: varchar("place_of_supply", { length: 100 }),
    isValidFrom: date("valid_from"),
    isValidUntil: date("valid_until"),
    isReverseCharge: boolean("is_reverse_charge").default(false).notNull(),
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("tax_templates_tenant_id_idx").on(t.tenantId),
    index("tax_templates_company_id_idx").on(t.companyId),
    index("tax_templates_type_idx").on(t.taxType),
    index("tax_templates_validity_idx").on(t.isValidFrom, t.isValidUntil),
  ]
);

// =============================================================================
// 16. TAX TEMPLATE RATES — Alíquotas do imposto (múltiplas faixas)
// =============================================================================
export const taxTemplateRates = pgTable(
  "tax_template_rates",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    templateId: uuid("template_id")
      .notNull()
      .references(() => taxTemplates.id, { onDelete: "cascade" }),
    rateName: varchar("rate_name", { length: 255 }).notNull(),
    rate: decimal("rate", { precision: 5, scale: 2 }).notNull(),
    minimumAmount: decimal("minimum_amount", { precision: 20, scale: 4 }),
    maximumAmount: decimal("maximum_amount", { precision: 20, scale: 4 }),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    isValidFrom: date("valid_from"),
    isValidUntil: date("valid_until"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("tax_template_rates_tenant_id_idx").on(t.tenantId),
    index("tax_template_rates_template_id_idx").on(t.templateId),
  ]
);

// =============================================================================
// 17. TAX WITHHOLDING CATEGORIES — Categorias de retenção na fonte
// =============================================================================
export const taxWithholdingCategories = pgTable(
  "tax_withholding_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    categoryName: varchar("category_name", { length: 255 }).notNull(),
    categoryCode: varchar("category_code", { length: 50 }),
    taxRate: decimal("tax_rate", { precision: 5, scale: 2 }).notNull(),
    minAmount: decimal("min_amount", { precision: 20, scale: 4 }),
    maxAmount: decimal("max_amount", { precision: 20, scale: 4 }),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    expenseAccountId: uuid("expense_account_id").references(() => chartOfAccounts.id),
    paymentTermType: varchar("payment_term_type", { length: 50 }), // cumulative, non_cumulative
    isValidFrom: date("valid_from"),
    isValidUntil: date("valid_until"),
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("tax_withholding_tenant_idx").on(t.tenantId),
    index("tax_withholding_company_idx").on(t.companyId),
    index("tax_withholding_validity_idx").on(t.isValidFrom, t.isValidUntil),
  ]
);

// =============================================================================
// 18. TAX WITHHOLDING RATES — Alíquotas de retenção (múltiplas faixas)
// =============================================================================
export const taxWithholdingRates = pgTable(
  "tax_withholding_rates",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => taxWithholdingCategories.id, { onDelete: "cascade" }),
    rateName: varchar("rate_name", { length: 255 }).notNull(),
    rate: decimal("rate", { precision: 5, scale: 2 }).notNull(),
    minAmount: decimal("min_amount", { precision: 20, scale: 4 }),
    maxAmount: decimal("max_amount", { precision: 20, scale: 4 }),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    isValidFrom: date("valid_from"),
    isValidUntil: date("valid_until"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("tax_withholding_rates_tenant_idx").on(t.tenantId),
    index("tax_withholding_rates_category_idx").on(t.categoryId),
  ]
);

// =============================================================================
// 19. TAX WITHHOLDING ENTRIES — Entradas de retenção na fonte
// =============================================================================
export const taxWithholdingEntries = pgTable(
  "tax_withholding_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    partyType: varchar("party_type", { length: 50 }).notNull(),
    partyId: uuid("party_id").notNull(),
    referenceType: varchar("reference_type", { length: 50 }).notNull(), // payment_entry, invoice, journal_entry
    referenceName: varchar("reference_name", { length: 255 }).notNull(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => taxWithholdingCategories.id),
    withholdingDate: date("withholding_date").notNull(),
    baseAmount: decimal("base_amount", { precision: 20, scale: 4 }).notNull(),
    withholdingRate: decimal("withholding_rate", { precision: 5, scale: 2 }).notNull(),
    withholdingAmount: decimal("withholding_amount", { precision: 20, scale: 4 }).notNull(),
    accountId: uuid("account_id").references(() => chartOfAccounts.id),
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    status: varchar("status", { length: 20 }).default("pending").notNull(), // pending, paid, cancelled
    paymentDate: date("payment_date"),
    remarks: text("remarks"),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("tax_withholding_entries_tenant_idx").on(t.tenantId),
    index("tax_withholding_entries_company_idx").on(t.companyId),
    index("tax_withholding_entries_party_idx").on(t.partyType, t.partyId),
    index("tax_withholding_entries_date_idx").on(t.withholdingDate),
    index("tax_withholding_entries_category_idx").on(t.categoryId),
    index("tax_withholding_entries_status_idx").on(t.status),
  ]
);

// =============================================================================
// 20. RECEIVABLE AGING SNAPSHOTS — Snapshots de aging de contas a receber
// =============================================================================
export const receivableAgingSnapshots = pgTable(
  "receivable_aging_snapshots",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    snapshotDate: date("snapshot_date").notNull(),
    partyType: varchar("party_type", { length: 50 }).notNull(),
    partyId: uuid("party_id").notNull(),
    partyName: varchar("party_name", { length: 255 }),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    totalOutstanding: decimal("total_outstanding", { precision: 20, scale: 4 }).default("0"),
    current: decimal("current", { precision: 20, scale: 4 }).default("0"),
    days30: decimal("days_30", { precision: 20, scale: 4 }).default("0"),
    days60: decimal("days_60", { precision: 20, scale: 4 }).default("0"),
    days90: decimal("days_90", { precision: 20, scale: 4 }).default("0"),
    over90: decimal("over_90", { precision: 20, scale: 4 }).default("0"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("receivable_aging_tenant_idx").on(t.tenantId),
    index("receivable_aging_company_idx").on(t.companyId),
    index("receivable_aging_date_idx").on(t.snapshotDate),
    index("receivable_aging_party_idx").on(t.partyType, t.partyId),
  ]
);

// =============================================================================
// 21. PAYABLE AGING SNAPSHOTS — Snapshots de aging de contas a pagar
// =============================================================================
export const payableAgingSnapshots = pgTable(
  "payable_aging_snapshots",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    snapshotDate: date("snapshot_date").notNull(),
    partyType: varchar("party_type", { length: 50 }).notNull(),
    partyId: uuid("party_id").notNull(),
    partyName: varchar("party_name", { length: 255 }),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    totalOutstanding: decimal("total_outstanding", { precision: 20, scale: 4 }).default("0"),
    current: decimal("current", { precision: 20, scale: 4 }).default("0"),
    days30: decimal("days_30", { precision: 20, scale: 4 }).default("0"),
    days60: decimal("days_60", { precision: 20, scale: 4 }).default("0"),
    days90: decimal("days_90", { precision: 20, scale: 4 }).default("0"),
    over90: decimal("over_90", { precision: 20, scale: 4 }).default("0"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("payable_aging_tenant_idx").on(t.tenantId),
    index("payable_aging_company_idx").on(t.companyId),
    index("payable_aging_date_idx").on(t.snapshotDate),
    index("payable_aging_party_idx").on(t.partyType, t.partyId),
  ]
);

// =============================================================================
// 22. ASSET CATEGORIES, ASSETS, DEPRECIATION ENTRIES — Defined in assets.ts
// =============================================================================

// =============================================================================
// 25. FINANCIAL STATEMENT CONFIGS — Configurações de demonstrativos financeiros
// =============================================================================
export const financialStatementConfigs = pgTable(
  "financial_statement_configs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    reportName: varchar("report_name", { length: 255 }).notNull(),
    reportType: varchar("report_type", { length: 50 }).notNull(), // balance_sheet, income_statement, cash_flow, trial_balance, general_ledger, accounts_receivable, accounts_payable
    description: text("description"),
    filterData: jsonb("filter_data").default({}),
    headerJson: jsonb("header_json").default({}),
    footerJson: jsonb("footer_json").default({}),
    isEnabled: boolean("is_enabled").default(true).notNull(),
    isDefault: boolean("is_default").default(false).notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("financial_report_configs_tenant_idx").on(t.tenantId),
    index("financial_report_configs_company_idx").on(t.companyId),
    index("financial_report_configs_type_idx").on(t.reportType),
  ]
);

// =============================================================================
// 26. REPORT COLUMNS — Colunas dos relatórios
// =============================================================================
export const reportColumns = pgTable(
  "report_columns",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    reportConfigId: uuid("report_config_id")
      .notNull()
      .references(() => financialStatementConfigs.id, { onDelete: "cascade" }),
    columnName: varchar("column_name", { length: 255 }).notNull(),
    columnType: varchar("column_type", { length: 50 }).notNull(), // data, calculated, text, period
    dataType: varchar("data_type", { length: 50 }), // decimal, integer, text, date, percentage
    formula: text("formula"),
    width: integer("width").default(150),
    isVisible: boolean("is_visible").default(true).notNull(),
    alignment: varchar("alignment", { length: 20 }).default("right"),
    formatString: varchar("format_string", { length: 50 }),
    rowIndex: integer("row_index").default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("report_columns_tenant_idx").on(t.tenantId),
    index("report_columns_config_idx").on(t.reportConfigId),
  ]
);

// =============================================================================
// 27. REPORT ROWS — Linhas dos relatórios
// =============================================================================
export const reportRows = pgTable(
  "report_rows",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    reportConfigId: uuid("report_config_id")
      .notNull()
      .references(() => financialStatementConfigs.id, { onDelete: "cascade" }),
    rowLabel: varchar("row_label", { length: 255 }).notNull(),
    rowType: varchar("row_type", { length: 50 }).notNull(), // header, data, calculated, section, total, grand_total
    accountType: varchar("account_type", { length: 50 }), // asset, liability, equity, income, expense
    accountSubtype: varchar("account_subtype", { length: 50 }),
    accountRangeStart: varchar("account_range_start", { length: 50 }),
    accountRangeEnd: varchar("account_range_end", { length: 50 }),
    accountIds: jsonb("account_ids").default([]),
    formula: text("formula"),
    indentLevel: integer("indent_level").default(0),
    rowIndex: integer("row_index").default(0),
    isVisible: boolean("is_visible").default(true).notNull(),
    isBold: boolean("is_bold").default(false).notNull(),
    isItalic: boolean("is_italic").default(false).notNull(),
    isUnderline: boolean("is_underline").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("report_rows_tenant_idx").on(t.tenantId),
    index("report_rows_config_idx").on(t.reportConfigId),
    index("report_rows_type_idx").on(t.rowType),
  ]
);

// =============================================================================
// 28. COMPANY ACCOUNTS — Contas padrão por empresa
// =============================================================================
export const companyAccounts = pgTable(
  "company_accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    accountType: varchar("account_type", { length: 100 }).notNull(), // default_bank_account, default_cash_account, default_receivable, default_payable, round_off_account, exchange_gain_loss, tax_account, depreciation_account, accumulated_depreciation, gain_on_disposal, loss_on_disposal
    accountId: uuid("account_id")
      .notNull()
      .references(() => chartOfAccounts.id),
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("company_accounts_tenant_id_idx").on(t.tenantId),
    index("company_accounts_company_id_idx").on(t.companyId),
    index("company_accounts_type_idx").on(t.accountType),
    uniqueIndex("company_accounts_type_company_idx").on(t.accountType, t.companyId),
  ]
);

// =============================================================================
// 29. COST CENTERS — Centros de custo COMPLETO com hierarquia
// =============================================================================
export const costCenterHierarchy = pgTable(
  "cost_center_hierarchy",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    costCenterId: uuid("cost_center_id")
      .notNull()
      .references(() => costCenters.id, { onDelete: "cascade" }),
    parentCostCenterId: uuid("parent_cost_center_id").references(() => costCenters.id),
    level: integer("level").default(0),
    path: varchar("path", { length: 500 }),
    description: text("description"),
    budgetAmount: decimal("budget_amount", { precision: 20, scale: 4 }).default("0"),
    actualAmount: decimal("actual_amount", { precision: 20, scale: 4 }).default("0"),
    variance: decimal("variance", { precision: 20, scale: 4 }).default("0"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("cost_center_hierarchy_tenant_idx").on(t.tenantId),
    index("cost_center_hierarchy_company_idx").on(t.companyId),
    index("cost_center_hierarchy_cost_center_idx").on(t.costCenterId),
    index("cost_center_hierarchy_parent_idx").on(t.parentCostCenterId),
  ]
);

// =============================================================================
// 30. FISCAL YEARS — Anos fiscais (mantido em core.ts, referência aqui)
// =============================================================================

// =============================================================================
// 31. CURRENCIES — Moedas (mantido em core.ts, referência aqui)
// =============================================================================

// =============================================================================
// 32. EXCHANGE RATES — Taxas de câmbio (mantido em core.ts, referência aqui)
// =============================================================================

// =============================================================================
// 33. DUNNING TYPES — Tipos de cobrança
// =============================================================================
export const dunningTypes = pgTable(
  "dunning_types",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    typeName: varchar("type_name", { length: 255 }).notNull(),
    dunningLevel: integer("dunning_level").default(1).notNull(),
    gracePeriodDays: integer("grace_period_days").default(0),
    minimumAmount: decimal("minimum_amount", { precision: 20, scale: 4 }),
    feeAmount: decimal("fee_amount", { precision: 20, scale: 4 }).default("0"),
    feePercentage: decimal("fee_percentage", { precision: 5, scale: 2 }).default("0"),
    interestRatePerDay: decimal("interest_rate_per_day", { precision: 5, scale: 2 }).default("0"),
    letterText: text("letter_text"),
    subjectTemplate: varchar("subject_template", { length: 500 }),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("dunning_types_tenant_idx").on(t.tenantId),
    index("dunning_types_company_idx").on(t.companyId),
  ]
);

// =============================================================================
// 34. DUNNING LETTERS — Defined in dunning.ts
// =============================================================================

// =============================================================================
// 35-37. SUBSCRIPTIONS — Defined in subscriptions.ts
// =============================================================================

// =============================================================================
// 38. CURRENCY CONVERSIONS — Conversões de moeda
// =============================================================================
export const currencyConversions = pgTable(
  "currency_conversions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    fromCurrency: varchar("from_currency", { length: 3 }).notNull(),
    toCurrency: varchar("to_currency", { length: 3 }).notNull(),
    exchangeRate: decimal("exchange_rate", { precision: 20, scale: 10 }).notNull(),
    reverseRate: decimal("reverse_rate", { precision: 20, scale: 10 }),
    conversionDate: date("conversion_date").notNull(),
    referenceType: varchar("reference_type", { length: 50 }), // journal_entry, payment_entry, invoice
    referenceName: varchar("reference_name", { length: 255 }),
    sourceAmount: decimal("source_amount", { precision: 20, scale: 4 }).notNull(),
    targetAmount: decimal("target_amount", { precision: 20, scale: 4 }).notNull(),
    realizedGainLoss: decimal("realized_gain_loss", { precision: 20, scale: 4 }).default("0"),
    journalEntryId: uuid("journal_entry_id").references(() => journalEntries.id),
    remarks: text("remarks"),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("currency_conversions_tenant_idx").on(t.tenantId),
    index("currency_conversions_company_idx").on(t.companyId),
    index("currency_conversions_pair_idx").on(t.fromCurrency, t.toCurrency),
    index("currency_conversions_date_idx").on(t.conversionDate),
    index("currency_conversions_reference_idx").on(t.referenceType, t.referenceName),
  ]
);

// =============================================================================
// 39. ACCOUNTING DIMENSIONS — Dimensões contábeis customizáveis
// =============================================================================
export const accountingDimensions = pgTable(
  "accounting_dimensions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    dimensionName: varchar("dimension_name", { length: 255 }).notNull(),
    dimensionType: varchar("dimension_type", { length: 50 }).notNull(), // text, number, date, select, link
    description: text("description"),
    defaultValue: varchar("default_value", { length: 255 }),
    options: jsonb("options"), // for select type: ["option1", "option2"]
    linkDoctype: varchar("link_doctype", { length: 100 }), // for link type
    isMandatory: boolean("is_mandatory").default(false).notNull(),
    isValidFor: jsonb("valid_for").default([]), // ["Journal Entry", "Sales Invoice", etc.]
    isActive: boolean("is_active").default(true).notNull(),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("accounting_dimensions_tenant_idx").on(t.tenantId),
    index("accounting_dimensions_company_idx").on(t.companyId),
  ]
);

// =============================================================================
// 40. ACCOUNTING DIMENSION VALUES — Valores das dimensões
// =============================================================================
export const accountingDimensionValues = pgTable(
  "accounting_dimension_values",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    dimensionId: uuid("dimension_id")
      .notNull()
      .references(() => accountingDimensions.id, { onDelete: "cascade" }),
    referenceType: varchar("reference_type", { length: 100 }).notNull(), // Journal Entry, Sales Invoice, Payment Entry, etc.
    referenceName: varchar("reference_name", { length: 255 }).notNull(),
    value: varchar("value", { length: 500 }).notNull(),
    numericValue: decimal("numeric_value", { precision: 20, scale: 4 }),
    dateValue: date("date_value"),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("accounting_dim_values_tenant_idx").on(t.tenantId),
    index("accounting_dim_values_dimension_idx").on(t.dimensionId),
    index("accounting_dim_values_reference_idx").on(t.referenceType, t.referenceName),
    index("accounting_dim_values_value_idx").on(t.value),
  ]
);

// =============================================================================
// 41. FINANCIAL STATEMENT REPORTS — Relatórios gerados (snapshot)
// =============================================================================
export const financialStatementReports = pgTable(
  "financial_statement_reports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    reportConfigId: uuid("report_config_id").references(() => financialStatementConfigs.id),
    reportName: varchar("report_name", { length: 255 }).notNull(),
    reportType: varchar("report_type", { length: 50 }).notNull(),
    filterData: jsonb("filter_data").default({}),
    reportData: jsonb("report_data").default({}),
    generatedBy: uuid("generated_by").references(() => users.id),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("financial_reports_tenant_idx").on(t.tenantId),
    index("financial_reports_company_idx").on(t.companyId),
    index("financial_reports_type_idx").on(t.reportType),
    index("financial_reports_config_idx").on(t.reportConfigId),
  ]
);
